// <auto-generated />
using System;
using AdvertApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AdvertApi.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20200623075336_AdvertApiMigration")]
    partial class AdvertApiMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AdvertApi.Models.Banner", b =>
                {
                    b.Property<int>("IdAdvertisement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Area")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<int>("IdCampaing")
                        .HasColumnType("int");

                    b.Property<int>("Name")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(6, 2)");

                    b.HasKey("IdAdvertisement");

                    b.ToTable("Banner");

                    b.HasData(
                        new
                        {
                            IdAdvertisement = 1,
                            Area = 1000.0m,
                            IdCampaing = 1,
                            Name = 1,
                            Price = 100.99m
                        },
                        new
                        {
                            IdAdvertisement = 2,
                            Area = 500.0m,
                            IdCampaing = 2,
                            Name = 2,
                            Price = 2000.5m
                        },
                        new
                        {
                            IdAdvertisement = 3,
                            Area = 100.0m,
                            IdCampaing = 3,
                            Name = 3,
                            Price = 30000.0m
                        },
                        new
                        {
                            IdAdvertisement = 4,
                            Area = 2500.0m,
                            IdCampaing = 4,
                            Name = 4,
                            Price = 40000.5m
                        });
                });

            modelBuilder.Entity("AdvertApi.Models.Building", b =>
                {
                    b.Property<int>("IdBuilding")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("StreetNumber")
                        .HasColumnType("int");

                    b.HasKey("IdBuilding");

                    b.ToTable("Building");

                    b.HasData(
                        new
                        {
                            IdBuilding = 1,
                            City = "Warszawa",
                            Height = 50.5m,
                            Street = "A",
                            StreetNumber = 1
                        },
                        new
                        {
                            IdBuilding = 2,
                            City = "Warszawa",
                            Height = 30.0m,
                            Street = "B",
                            StreetNumber = 2
                        },
                        new
                        {
                            IdBuilding = 3,
                            City = "Warszawa",
                            Height = 70.5m,
                            Street = "C",
                            StreetNumber = 3
                        },
                        new
                        {
                            IdBuilding = 4,
                            City = "Warszawa",
                            Height = 34.5m,
                            Street = "D",
                            StreetNumber = 4
                        });
                });

            modelBuilder.Entity("AdvertApi.Models.Campaign", b =>
                {
                    b.Property<int>("IdCampaign")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FromIdBuilding")
                        .HasColumnType("int");

                    b.Property<int>("IdClient")
                        .HasColumnType("int");

                    b.Property<decimal>("PricePerSquareMeter")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ToldBuilding")
                        .HasColumnType("int");

                    b.HasKey("IdCampaign");

                    b.ToTable("Campaign");

                    b.HasData(
                        new
                        {
                            IdCampaign = 1,
                            EndDate = new DateTime(2020, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FromIdBuilding = 1,
                            IdClient = 1,
                            PricePerSquareMeter = 5000.0m,
                            StartDate = new DateTime(2020, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ToldBuilding = 2
                        },
                        new
                        {
                            IdCampaign = 2,
                            EndDate = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FromIdBuilding = 2,
                            IdClient = 2,
                            PricePerSquareMeter = 10000.5m,
                            StartDate = new DateTime(2020, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ToldBuilding = 3
                        },
                        new
                        {
                            IdCampaign = 3,
                            EndDate = new DateTime(2020, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FromIdBuilding = 3,
                            IdClient = 3,
                            PricePerSquareMeter = 20000.0m,
                            StartDate = new DateTime(2020, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ToldBuilding = 4
                        },
                        new
                        {
                            IdCampaign = 4,
                            EndDate = new DateTime(2021, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FromIdBuilding = 4,
                            IdClient = 4,
                            PricePerSquareMeter = 100000.99m,
                            StartDate = new DateTime(2020, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ToldBuilding = 1
                        });
                });

            modelBuilder.Entity("AdvertApi.Models.Client", b =>
                {
                    b.Property<int>("IdClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdClient");

                    b.ToTable("Client");

                    b.HasData(
                        new
                        {
                            IdClient = 1,
                            Email = "Jan@maiil.com",
                            FirstName = "Jan",
                            LastName = "A",
                            Login = "JanA",
                            Password = "abbbb",
                            Phone = "100 200 300"
                        },
                        new
                        {
                            IdClient = 2,
                            Email = "Adam@maiil.com",
                            FirstName = "Adam",
                            LastName = "B",
                            Login = "Adam1",
                            Password = "abssss",
                            Phone = "200 300 400"
                        },
                        new
                        {
                            IdClient = 3,
                            Email = "Anna@maiil.com",
                            FirstName = "Anna",
                            LastName = "C",
                            Login = "Anna1",
                            Password = "asdadabbb",
                            Phone = "900 888 111"
                        },
                        new
                        {
                            IdClient = 4,
                            Email = "Karol@maiil.com",
                            FirstName = "Karol",
                            LastName = "D",
                            Login = "Karol",
                            Password = "abadsadxxbbb",
                            Phone = "000 333 444"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
